# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            "auntie's blag"
tagline:          'part of this complete breakfast'
description:      'A place where <a href="https://github.com/auntieNeo">Jonathan Glines</a> sometimes writes stuff about programming, Linux, game devolpment, and Japanese.'
url:              http://www.auntieNeo.net
paginate:         5

site:
  baseurl:        '/'

author:
  name:           'Jonathan Glines'
  url:            https://github.com/auntieNeo

github:
  profile:        https://github.com/auntieNeo
